version: '3.8'
services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: 'redis:7-alpine'
    restart: unless-stopped
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=${POSTGRES_PASSWORD:-postgres_password}
      - PGPORT=5432
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - REACT_APP_API_URL=http://localhost/api
    restart: unless-stopped
  
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data: 