apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: multi-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/${{ github.repository }}-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: REDIS_PORT
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: PGUSER
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: PGHOST
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: PGDATABASE
        - name: PGPASSWORD
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: POSTGRES_PASSWORD
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: PGPORT
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: multi-docker
spec:
  selector:
    app: api
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP 