apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-docker-config
  namespace: multi-docker
data:
  POSTGRES_PASSWORD: "postgres_password"
  POSTGRES_DB: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  PGUSER: "postgres"
  PGHOST: "postgres-service"
  PGDATABASE: "postgres"
  PGPORT: "5432" 