apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: multi-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ghcr.io/${{ github.repository }}-worker:latest
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: multi-docker-config
              key: REDIS_PORT
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m" 