# Default values for multi-docker
replicaCount:
  api: 2
  worker: 2
  client: 2

image:
  repository: ghcr.io/your-username/multi-docker
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: multi-docker.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls: []

resources:
  api:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  worker:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  client:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

env:
  POSTGRES_PASSWORD: "postgres_password"
  POSTGRES_DB: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  PGUSER: "postgres"
  PGHOST: "postgres-service"
  PGDATABASE: "postgres"
  PGPORT: "5432"
  NODE_ENV: "production" 